// Automaticaly generated by rust_swig
package xyz.ecumene.jgilrs;

//Gamepad's elements which state can be represented by value from -1.0 to 1.0.
public enum Axis {
LeftStickX(0),
LeftStickY(1),
LeftZ(2),
RightStickX(3),
RightStickY(4),
RightZ(5),
DPadX(6),
DPadY(7),
Unknown(8);

    private int value;
    Axis(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
}
