// Automaticaly generated by rust_swig
package xyz.ecumene.jgilrs;

//Information about axis stored in State
public final class AxisData {

    private AxisData() {}
    //@return 0.0 - 1.0 value of axis.
    public final float getValue()  {

        return do_getValue(mNativeObj);
    }
    private static native float do_getValue(long me) ;
    //@return value of counter when axis value last changed.
    public final long getCounter()  {

        return do_getCounter(mNativeObj);
    }
    private static native long do_getCounter(long me) ;
    //@return when axis value last changed.
    public final java.util.Date getTimestamp()  {

        return do_getTimestamp(mNativeObj);
    }
    private static native java.util.Date do_getTimestamp(long me) ;

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ long mNativeObj;
}