// Automaticaly generated by rust_swig
package xyz.ecumene.jgilrs;


public enum BaseEffectTypeWrapper {
Strong(0),
Weak(1);

    private int value;
    BaseEffectTypeWrapper(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
}
