// Automaticaly generated by rust_swig
package xyz.ecumene.jgilrs;

//Information about button stored in State.
public final class ButtonData {

    private ButtonData() {}
    //@return true if button is pressed.
    public final boolean isPressed()  {

        return do_isPressed(mNativeObj);
    }
    private static native boolean do_isPressed(long me) ;
    //@return analog of button.
    public final float getValue()  {

        return do_getValue(mNativeObj);
    }
    private static native float do_getValue(long me) ;
    //@return true if button is repeating.
    public final boolean isRepeating()  {

        return do_isRepeating(mNativeObj);
    }
    private static native boolean do_isRepeating(long me) ;
    //@return 0.0 - 0.1 value of counter when button state last changed.
    public final long getCounter()  {

        return do_getCounter(mNativeObj);
    }
    private static native long do_getCounter(long me) ;
    //@return when button state last changed.
    public final java.util.Date getTimestamp()  {

        return do_getTimestamp(mNativeObj);
    }
    private static native java.util.Date do_getTimestamp(long me) ;

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ long mNativeObj;
}