// Automaticaly generated by rust_swig
package xyz.ecumene.jgilrs;

//Gamepad's elements which state can be represented by value from 0.0 to 1.0.
public enum Button {
South(0),
East(1),
North(2),
West(3),
C(4),
Z(5),
LeftTrigger(6),
LeftTrigger2(7),
RightTrigger(8),
RightTrigger2(9),
Select(10),
Start(11),
Mode(12),
LeftThumb(13),
RightThumb(14),
DPadUp(15),
DPadDown(16),
DPadLeft(17),
DPadRight(18),
Unknown(19);

    private int value;
    Button(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
}
