// Automaticaly generated by rust_swig
package xyz.ecumene.jgilrs;

//Creates new Effect.
public final class EffectBuilder {
    //Creates new builder with following defaults: no gamepads, no base effects, repeat set to infinitely, no distance model,
    //position in (0.0, 0.0, 0.0) and gain 1.0. Use finish() to create new effect.
    public EffectBuilder()  {

        mNativeObj = init();
    }
    private static native long init() ;
    //Adds new BaseEffect.
    public final EffectBuilder addEffect(BaseEffect a0)  {

        long a0C0 = a0.mNativeObj;
        a0.mNativeObj = 0;

        return do_addEffect(mNativeObj, a0C0);
    }
    private static native EffectBuilder do_addEffect(long me, long a0) ;
    //Adds gamepad to the list of gamepads associated with effect.
    public final EffectBuilder addGamepad(Gamepad a0)  {

        long a0C0 = a0.mNativeObj;

        return do_addGamepad(mNativeObj, a0C0);
    }
    private static native EffectBuilder do_addGamepad(long me, long a0) ;
    //Validates all parameters and creates new effect.
    //@return Effect or an error string
    public final Effect finish(Gilrs a0) throws Exception {

        long a0C0 = a0.mNativeObj;

        return do_finish(mNativeObj, a0C0);
    }
    private static native Effect do_finish(long me, long a0) throws Exception;

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ long mNativeObj;
}