// Automaticaly generated by rust_swig
package xyz.ecumene.jgilrs;

//Envelope shaped attenuation(time) function.
public final class Envelope {
    //@param attack_strength ticks - ms
    //@param attack_level level 0.0 - 1.0
    //@param fade_length ticks ms
    //@param fade_level level 0.0 - 1.0
    public Envelope(long a0, float a1, long a2, float a3)  {

        mNativeObj = init(a0, a1, a2, a3);
    }
    private static native long init(long a0, float a1, long a2, float a3) ;

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ long mNativeObj;
}