// Automaticaly generated by rust_swig
package xyz.ecumene.jgilrs;

//It's not possible to create instance of this type directly, but you can obtain
//one from Gamepad handle or any event. ID is valid for entire lifetime of Gilrs
//context.
public final class GamepadId {

    private GamepadId() {}

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ long mNativeObj;
}