// Automaticaly generated by rust_swig
package xyz.ecumene.jgilrs;

//State of device's power supply.
//
//Battery level is reported as integer between 0 and 100.
public final class PowerInfo {

    private PowerInfo() {}
    //The power status
    //Unknown: Failed to determine power status.
    //Wired: Device doesn't have battery.
    //Discharging: Device is running on the battery.
    //Charging: Battery is charging.
    //Charged: Battery is charged.
    public final String getStatus()  {

        return do_getStatus(mNativeObj);
    }
    private static native String do_getStatus(long me) ;
    //The power level (if applicable)
    //Only applied on charging or discharging
    public final short getValue()  {

        return do_getValue(mNativeObj);
    }
    private static native short do_getValue(long me) ;

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ long mNativeObj;
}