// Automaticaly generated by rust_swig
package xyz.ecumene.jgilrs;

//Represents duration.
//
//This type is only useful as input parameter for other functions for force
//feedback. Keep in mind that Ticks is not precise representation of time.
public final class Ticks {
    //A new ticks object
    //
    //@param ms Milliseconds representing a duration of time
    //@return a new tick object
    public Ticks(long a0)  {

        mNativeObj = init(a0);
    }
    private static native long init(long a0) ;

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ long mNativeObj;
}