/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package xyz.ecumene.jgilrs.natives;

import org.junit.Test;
import org.junit.experimental.categories.Category;

import xyz.ecumene.jgilrs.Library;

public class NativeTest {
    @Test
    public void initNative() throws Exception {
        Library.init();
    }
}
